apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
  namespace: patchdb
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: patchdb
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: k8.patchdb.se
    - name: https
      protocol: HTTPS
      port: 443
      hostname: k8.patchdb.se
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: patchdb-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: patchdb-routes
  namespace: patchdb
spec:
  parentRefs:
  - name: eg
  hostnames:
  - "k8.patchdb.se"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: backend-dotnet
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: patchdb-frontend
      port: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            # cert-manager will create temporary HTTPRoute(s) to solve the challenge
            parentRefs:
              - group: gateway.networking.k8s.io
                kind: Gateway
                name: eg
                namespace: patchdb
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: patchdb-tls
  namespace: patchdb
spec:
  secretName: patchdb-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8.patchdb.se
  dnsNames:
  - k8.patchdb.se